services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "127.0.0.1:5432:5432"
  bot:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    environment:
      DBHOST: postgres
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data:
